#!/bin/ksh
#
#  start_registry
#
#
#



JHOME="/usr/bin/java"

echo "\n\n\n\t starten der rmiregistry ...."

/usr/bin/rmiregistry&

sleep 4


echo "\n\n\t ==========================================="
echo "\n\t die rmiregistry laeuft  !!!"


set `ps -ef | fgrep rmiregistry | grep -v fgrep | tr -s " "`


echo "\n\t USER =  $1\n\t PID = $2\n\t REGISTRY = $8\n\n"

