ping -6 stl-v-175.stl.htwsaar.de
ping -6 stl-s-stud.stl.htwsaar.de
ping -6 www.htwsaar.de
ping -6 www.uni-saarland.de
ping -6 www.uni-kaiserslautern.de
ping -6 www.dfn.de
ping -6 www.zeit.de
ping -6 ws-ber1.win-ip.dfn.de
ping -6  www.nasa.gov
ping -6  www.nasa.com
ping -6 www.washington.org
ping -6 www.sydney.com
