#   Makefile ---> persoenliches JAVA Makefile
#
#
#


# Voreinstellungen fuer den java-compiler
#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

include /export/home_pm/bin/java-make.rules


# Eigene Make-Regeln
#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
