#   Makefile ---> persoenliches Makefile
#
#
#


# Voreinstellungen fuer den gcc und g++
#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

include /export/home_pm/bin/gnu-make.rules


# Eigene Make-Regeln
#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

CLIBS= -lsocket -lnsl
