#   Makefile ---> persoenliches Makefile
#
#
#


# Voreinstellungen fuer den gcc und g++
#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

include /export/home_pm/bin/gnu-make.rules-Solaris


# Eigene Make-Regeln
#vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

CLIBS = -lsocket -lnsl

clean:
	rm client server
