/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RLS_H_RPCGEN
#define	_RLS_H_RPCGEN

#include <rpc/rpc.h>
#define	MAXNAMELEN 255

typedef char *nametype;

typedef struct namenode *namelist;

struct namenode {
	nametype name;
	namelist next;
};
typedef struct namenode namenode;

struct readdir_res {
	int errno;
	union {
		namelist list;
	} readdir_res_u;
};
typedef struct readdir_res readdir_res;

#define	DIRPROG	0x20000076
#define	DIRVERS	1
#define	READDIR	1
extern  readdir_res * readdir_1();
extern int dirprog_1_freeresult();

/* the xdr functions */
extern bool_t xdr_nametype();
extern bool_t xdr_namelist();
extern bool_t xdr_namenode();
extern bool_t xdr_readdir_res();

#endif /* !_RLS_H_RPCGEN */
