/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rls.h"

bool_t
xdr_nametype(xdrs, objp)
	register XDR *xdrs;
	nametype *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_string(xdrs, objp, MAXNAMELEN))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_namelist(xdrs, objp)
	register XDR *xdrs;
	namelist *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_pointer(xdrs, (char **)objp, sizeof (struct namenode), (xdrproc_t) xdr_namenode))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_namenode(xdrs, objp)
	register XDR *xdrs;
	namenode *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_nametype(xdrs, &objp->name))
		return (FALSE);
	if (!xdr_namelist(xdrs, &objp->next))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_readdir_res(xdrs, objp)
	register XDR *xdrs;
	readdir_res *objp;
{

#if defined(_LP64) || defined(_KERNEL)
	register int *buf;
#else
	register long *buf;
#endif

	if (!xdr_int(xdrs, &objp->errno))
		return (FALSE);
	switch (objp->errno) {
	case 0:
		if (!xdr_namelist(xdrs, &objp->readdir_res_u.list))
			return (FALSE);
		break;
	}
	return (TRUE);
}
